import Head from 'next/head'

export default function HeadPage() {
    return (
        <Head>
            <title>Demo NextJS</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
    )
}